apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-config
  namespace: banking

data:
  SPRING_PROFILES_ACTIVE: "default"
  SERVER_PORT: "8080"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "customer_db"
  