apiVersion: v1
kind: Secret #Sensitive information ke liye Kubernetes object.
metadata: 
  name: customer-db-secret
  namaspace: banking

type: Opaque
stringData: 
  POSTGRES_DB: customer_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

