apiVersion: v1
kind: Service

metadata:
  name: customer-service
  namespace: banking

spec:
  selector:
    app: customer-service

  ports:
    - name: http
      port: 80
      targetPort: 8082

  type: ClusterIP