spring.application.name=auth-service
server.port=8001
spring.cloud.config.import-check.enabled=false
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update