spring.application.name=notification-service
management.tracing.enabled=true #enables Micrometer Tracing in your Spring Boot application
management.tracing.sampling.probability=1.0 #controls how many requests should be traced.
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans