services:
  config-server:
    build:
      context: config-server
      dockerfile: Dockerfile
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - banking-network

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8001:8001"
    networks:
      - banking-network

  customer-service:
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    container_name: customer-service
    ports:
      - "8002:8002"
    environment:
      DB_USER: root
      DB_PASSWORD: root123
      RAZOR_KEY_ID: ${RAZOR_KEY_ID}
      RAZOR_KEY_SECRET: ${RAZOR_KEY_SECRET}
    depends_on:
      - config-server
      - postgres
      - redis
    networks:
      - banking-network

  

  account-service:
    build: ./account-service
    ports:
      - "8003:8003"

  credit-service:
    build: ./credit-service
    ports:
      - "8004:8004"

  fraud-deductions-service:
    build: ./fraud-detection-service
    ports:
      - "8005:8005"

  notification-service:
    build: ./notification-service
    ports:
      - "8006:8006"

  transaction-service:
    build: ./transaction-service
    ports:
      - "8008:8008"

