spring.application.name=transaction-service
account.service.url=http://localhost:8007
fraud.max-balance-percentage=0.90
fraud.suspicious-amount-multiplier=5000
fraud.max-transaction-per-minute=5
outbox.transaction.event.scheduler.delay=5s

# kafka properties
#Prevents message loss by waiting for all in-sync replicas.
spring.kafka.producer.acks=all
#Automatically retries transient failures.
spring.kafka.producer.retries=10
#Prevents duplicate messages caused by retries.
spring.kafka.producer.properties.enable.idempotence=true
#Preserves ordering while using idempotence.
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5
#Limits the total time spent trying to deliver a message.
spring.kafka.producer.properties.delivery.timeout.ms=120000
#Defines how long to wait for a broker response before retrying.
spring.kafka.producer.properties.request.timeout.ms=30000
#Waits briefly between retry attempts to avoid overwhelming the broker.
spring.kafka.producer.properties.retry.backoff.ms=1000
spring.kafka.producer.properties.spring.json.add.type.headers=false
spring.data.redis.host=localhost
spring.data.redis.port=6739