 spring.main.web-application-type=reactive
management.tracing.enabled=true
management.tracing.sampling.probability=1.0

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [traceId=%X{traceId}, spanId=%X{spanId}] %logger{36} - %msg%n
