# ============================================================
# PostgreSQL Persistent Volume Claim
# ============================================================
#
# Ye bahut important file hai.
#
# Kyun?
#
# PostgreSQL ka data container ke andar directly nahi rakhna chahiye.
#
# Agar PostgreSQL Pod delete ho gaya:
#
# PostgreSQL Pod
#      |
#      └── Container filesystem
#               |
#               └── DATA ❌
#
# Pod recreate hone par container filesystem ka data lose
# ho sakta hai.
#
# Isliye PostgreSQL ka data Persistent Volume (PV) par store
# karenge.
#
# PVC = PersistentVolumeClaim
#
# PVC Kubernetes se storage maangta hai.
# ============================================================

apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: postgres-pvc
  namespace: banking

spec:

  # ==========================================================
  # Access Mode
  # ==========================================================
  #
  # ReadWriteOnce (RWO)
  # Volume ek node par read/write mode mein mount ho sakta hai.
  #
  # PostgreSQL ke single Pod setup ke liye ye suitable hai.
  # ==========================================================

  accessModes:
    - ReadWriteOnce

  # ==========================================================
  # Storage Request
  # ==========================================================
  #
  # Kubernetes se 20Gi storage request kar rahe hain.
  #
  # NOTE:
  # 20Gi = approximately 20 GB
  # ==========================================================

  resources:
    requests:
      storage: 1Gi
