spring:
  application:
    name: account-service

  datasource:
    url: jdbc:mysql://localhost:3306/account_db?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:banking_user}
    password: ${DB_PASSWORD:change-me}

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000 #If no connection becomes available within the timeout: SQLTransientConnectionException
      idle-timeout: 600000 #Controls how long idle connections can remain in the pool when the pool has more than the configured minimum idle connections.
      max-lifetime: 1800000

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring:
          json:
            trusted:
              packages: "*"
            use:
              type:
                headers: false

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      timeout: 5000ms

      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka/}

    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: true

management:
  tracing:
    enabled: true

    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:1.0}

  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://zipkin:9411/api/v2/spans}

  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.banking: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.springframework.cache: TRACE
    org.hibernate.SQL: TRACE

  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html
