apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
  namespace: banking

spec:
  replicas: 1

  selector:
    matchLabels:
      app: discovery-service

  template:
    metadata:
      labels:
        app: discovery-service

    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001

      containers:
        - name: discovery-service

          image: ${FULL_IMAGE}
          imagePullPolicy: Always

          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            allowPrivilegeEscalation: false

          ports:
            - name: http
              containerPort: 8761
              protocol: TCP

          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"

            limits:
              memory: "512Mi"
              cpu: "500m"

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8761
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8761
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3