apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
  namespace: banking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: rajvi1023/discovery-service:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8761

          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"