pipeline {
    agent any

    environment {
        IMAGE_NAME = 'rajvi1023/auth-service'
        IMAGE_TAG  = "${BUILD_NUMBER}"
        FULL_IMAGE = "${IMAGE_NAME}:${IMAGE_TAG}"
    }

    stages {

        // =========================================================
        // 1. BUILD
        // =========================================================

        stage('Build') {
            steps {
                dir('auth-service') {
                    sh '''
                        set -e

                        echo "======================================"
                        echo "MAVEN BUILD"
                        echo "======================================"

                        mvn clean verify -DskipTests
                    '''
                }
            }
        }

        // =========================================================
        // 2. DOCKER BUILD
        // =========================================================

        stage('Docker Build') {
            steps {
                dir('auth-service') {
                    sh '''
                        set -e

                        echo "======================================"
                        echo "DOCKER BUILD"
                        echo "======================================"

                        echo "Building image:"
                        echo "${FULL_IMAGE}"

                        docker build \
                            -t ${FULL_IMAGE} \
                            .
                    '''
                }
            }
        }

        // =========================================================
        // 3. DOCKER PUSH
        // =========================================================

        stage('Docker Push') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub',
                        usernameVariable: 'DOCKER_USERNAME',
                        passwordVariable: 'DOCKER_PASSWORD'
                    )
                ]) {
                    sh '''
                        set -e

                        echo "======================================"
                        echo "DOCKER PUSH"
                        echo "======================================"

                        echo "$DOCKER_PASSWORD" | docker login \
                            -u "$DOCKER_USERNAME" \
                            --password-stdin

                        docker push ${FULL_IMAGE}

                        docker logout
                    '''
                }
            }
        }

        // =========================================================
        // 4. VERIFY KUBERNETES
        // =========================================================

        stage('Verify Kubernetes Connection') {
            steps {
                sh '''
                    set -e

                    echo "======================================"
                    echo "VERIFY KUBERNETES"
                    echo "======================================"

                    echo "kubectl version:"
                    kubectl version --client

                    echo ""
                    echo "Current context:"
                    kubectl config current-context

                    echo ""
                    echo "Cluster info:"
                    kubectl cluster-info

                    echo ""
                    echo "Nodes:"
                    kubectl get nodes

                    echo ""
                    echo "Namespaces:"
                    kubectl get namespaces
                '''
            }
        }

        // =========================================================
        // 5. DEPLOY BANKING NAMESPACE
        // =========================================================

        stage('Deploy Banking Namespace') {
            steps {
                dir('auth-service') {
                    sh '''
                        set -e

                        echo "======================================"
                        echo "DEPLOY BANKING NAMESPACE"
                        echo "======================================"

                        kubectl apply \
                            -f k8s/auth/namespace.yaml

                        kubectl get namespace banking
                    '''
                }
            }
        }

        // =========================================================
        // 6. DEPLOY AUTH MYSQL
        // =========================================================

        stage('Deploy Auth MySQL') {
            steps {
                dir('auth-service') {
                    sh '''
                        set -e

                        echo "======================================"
                        echo "DEPLOY AUTH MYSQL"
                        echo "======================================"

                        kubectl apply \
                            -f k8s/mysql/mysql-secret.yaml

                        kubectl apply \
                            -f k8s/mysql/mysql-deployment.yaml

                        kubectl apply \
                            -f k8s/mysql/mysql-service.yaml

                        echo ""
                        echo "MySQL resources:"
                        kubectl get all \
                            -n banking \
                            -l app=mysql

                        echo ""
                        echo "MySQL Service:"
                        kubectl get svc \
                            -n banking \
                            mysql

                        echo ""
                        echo "Waiting for MySQL..."

                        if ! kubectl rollout status \
                            deployment/mysql \
                            -n banking \
                            --timeout=180s
                        then

                            echo "======================================"
                            echo "AUTH MYSQL DEPLOYMENT FAILED"
                            echo "======================================"

                            echo ""
                            echo "Pods:"
                            kubectl get pods \
                                -n banking \
                                -l app=mysql \
                                -o wide

                            echo ""
                            echo "Services:"
                            kubectl get svc \
                                -n banking

                            echo ""
                            echo "Endpoints:"
                            kubectl get endpoints \
                                -n banking

                            echo ""
                            echo "MySQL Logs:"
                            kubectl logs \
                                -n banking \
                                -l app=mysql \
                                --tail=100 || true

                            echo ""
                            echo "MySQL Describe:"
                            kubectl describe pod \
                                -n banking \
                                -l app=mysql || true

                            echo ""
                            echo "Kubernetes Events:"
                            kubectl get events \
                                -n banking \
                                --sort-by=.lastTimestamp \
                                | tail -30

                            exit 1
                        fi

                        echo ""
                        echo "MySQL is READY!"
                    '''
                }
            }
        }

        // =========================================================
        // 7. DEPLOY AUTH CONFIG + SECRET
        // =========================================================

        stage('Deploy Auth Configuration') {
            steps {
                dir('auth-service') {
                    sh '''
                        set -e

                        echo "======================================"
                        echo "DEPLOY AUTH CONFIGURATION"
                        echo "======================================"

                        kubectl apply \
                            -f k8s/auth/auth-service-config.yaml

                        kubectl apply \
                            -f k8s/auth/auth-service-secret.yaml

                        echo ""
                        echo "Auth ConfigMap:"
                        kubectl get configmap \
                            auth-service-config \
                            -n banking

                        echo ""
                        echo "Auth Secret:"
                        kubectl get secret \
                            auth-service-secret \
                            -n banking
                    '''
                }
            }
        }

        // =========================================================
        // 8. DEPLOY AUTH SERVICE
        // =========================================================

        stage('Deploy Auth Service') {
            steps {
                dir('auth-service') {
                    sh '''
                        set -e

                        echo "======================================"
                        echo "DEPLOY AUTH SERVICE"
                        echo "======================================"

                        export IMAGE_TAG=${BUILD_NUMBER}

                        echo "Deploying image:"
                        echo "${FULL_IMAGE}"

                        echo ""
                        echo "Applying Auth Service Deployment..."

                        envsubst < \
                            k8s/auth/auth-service-deployment.yaml | \
                            kubectl apply -f -

                        echo ""
                        echo "Applying Auth Service Service..."

                        kubectl apply \
                            -f k8s/auth/auth-service-service.yaml

                        echo ""
                        echo "Waiting for Auth Service..."

                        if ! kubectl rollout status \
                            deployment/auth-service \
                            -n banking \
                            --timeout=180s
                        then

                            echo "======================================"
                            echo "AUTH SERVICE DEPLOYMENT FAILED"
                            echo "======================================"

                            echo ""
                            echo "Deployments:"
                            kubectl get deployments \
                                -n banking

                            echo ""
                            echo "Pods:"
                            kubectl get pods \
                                -n banking \
                                -o wide

                            echo ""
                            echo "Services:"
                            kubectl get svc \
                                -n banking

                            echo ""
                            echo "Endpoints:"
                            kubectl get endpoints \
                                -n banking

                            echo ""
                            echo "Auth Logs:"
                            kubectl logs \
                                -n banking \
                                -l app=auth-service \
                                --tail=150 || true

                            echo ""
                            echo "Auth Describe:"
                            kubectl describe deployment \
                                auth-service \
                                -n banking || true

                            echo ""
                            echo "Kubernetes Events:"
                            kubectl get events \
                                -n banking \
                                --sort-by=.lastTimestamp \
                                | tail -50

                            exit 1
                        fi

                        echo ""
                        echo "Auth Service is READY!"
                    '''
                }
            }
        }

        // =========================================================
        // 9. DEPLOY HPA
        // =========================================================

        stage('Deploy Auth HPA') {
            steps {
                dir('auth-service') {
                    sh '''
                        set -e

                        echo "======================================"
                        echo "DEPLOY AUTH HPA"
                        echo "======================================"

                        kubectl apply \
                            -f k8s/auth/auth-service-hpa.yaml

                        kubectl get hpa \
                            -n banking
                    '''
                }
            }
        }

        // =========================================================
        // 10. DEPLOY PDB
        // =========================================================

        stage('Deploy Auth PDB') {
            steps {
                dir('auth-service') {
                    sh '''
                        set -e

                        echo "======================================"
                        echo "DEPLOY AUTH PDB"
                        echo "======================================"

                        kubectl apply \
                            -f k8s/auth/auth-service-pdb.yaml

                        kubectl get pdb \
                            -n banking
                    '''
                }
            }
        }

        // =========================================================
        // 11. VERIFY KUBERNETES
        // =========================================================

        stage('Verify Kubernetes') {
            steps {
                sh '''
                    set -e

                    echo "======================================"
                    echo "KUBERNETES STATUS"
                    echo "======================================"

                    echo ""
                    echo "Deployments:"
                    kubectl get deployments \
                        -n banking

                    echo ""
                    echo "Pods:"
                    kubectl get pods \
                        -n banking \
                        -o wide

                    echo ""
                    echo "Services:"
                    kubectl get services \
                        -n banking

                    echo ""
                    echo "Endpoints:"
                    kubectl get endpoints \
                        -n banking

                    echo ""
                    echo "HPA:"
                    kubectl get hpa \
                        -n banking

                    echo ""
                    echo "PDB:"
                    kubectl get pdb \
                        -n banking

                    echo ""
                    echo "======================================"
                    echo "AUTH SERVICE DEPLOYMENT COMPLETE"
                    echo "======================================"
                '''
            }
        }

        // =========================================================
        // 12. GET AUTH SERVICE URL
        // =========================================================

        stage('Get Auth Service URL') {
            steps {
                sh '''
                    echo "======================================"
                    echo "AUTH SERVICE URL"
                    echo "======================================"

                    kubectl get svc \
                        auth-service \
                        -n banking

                    echo ""

                    minikube service \
                        auth-service \
                        -n banking \
                        --url || true

                    echo ""
                    echo "======================================"
                '''
            }
        }
    }

    post {

        success {
            echo """
            ======================================
            CI/CD SUCCESS
            ======================================

            Application : Auth Service
            Image       : ${FULL_IMAGE}
            Build       : ${BUILD_NUMBER}
            Namespace   : banking
            Port        : 8001

            Deployment completed successfully.

            ======================================
            """
        }

        failure {
            echo """
            ======================================
            CI/CD FAILED
            ======================================

            Application : Auth Service
            Build       : ${BUILD_NUMBER}
            Namespace   : banking

            Please check Jenkins logs.

            ======================================
            """
        }

        always {
            echo "Jenkins Build: ${BUILD_NUMBER}"
            echo "Result: ${currentBuild.currentResult}"
        }
    }
}
