pipeline {

    agent any

    environment {
        IMAGE = "rajvi1023/dashboard-service"
        TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Docker Build') {
            steps {
                sh """
                    docker build \
                    -t ${IMAGE}:${TAG} .
                """
            }
        }

        stage('Docker Push') {
            steps { 

                    sh """
                        echo \$PASSWORD | docker login \
                        -u \$USERNAME \
                        --password-stdin

                        docker push ${IMAGE}:${TAG}
                    """ 
            }
        }

        stage('Deploy Kubernetes') {
            steps {
                sh """
                    kubectl set image deployment/dashboard-service \
                    dashboard-service=${IMAGE}:${TAG}

                    kubectl rollout status \
                    deployment/dashboard-service
                """
            }
        }
    }
}
