pipeline {
    agent any

    environment {
        IMAGE_NAME = 'rajvi1023/dashboard-service'
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Debug') {
            steps {
                sh '''
                    echo "Workspace:"
                    pwd

                    echo "Files:"
                    ls -la

                    echo "Maven projects:"
                    find . -name pom.xml
                '''
            }
        }

        stage('Build') {
            steps {
                dir('dashboard-service') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Test') {
            steps {
                dir('dashboard-service') {
                    sh 'mvn test'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('dashboard-service') {
                    sh """
                        docker build \
                        -t ${IMAGE_NAME}:${IMAGE_TAG} .
                    """
                }
            }
        }

        stage('Docker Push') {
            steps {
                echo 'Docker push will happen here'
            }
        }

        stage('Deploy Kubernetes') {
            steps {
                sh """
                    kubectl set image deployment/dashboard-service \
                    dashboard-service=${IMAGE}:${TAG}

                    kubectl rollout status \
                    deployment/dashboard-service
                """
            }
        }
    }
}
