pipeline {
    agent any

    environment {
        IMAGE_NAME = 'rajvi1023/dashboard-service'
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        // stage('Debug') {
        //     steps {
        //         sh '''
        //             echo "Workspace:"
        //             pwd

        //             echo "Files:"
        //             ls -la

        //             echo "Maven projects:"
        //             find . -name pom.xml
        //         '''
        //     }
        // }

        stage('Build') {
            steps {
                dir('dashboard-service') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Test') {
            steps {
                dir('dashboard-service') {
                    sh 'mvn test'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('dashboard-service') {
                    sh """
                        docker build \
                        -t ${IMAGE_NAME}:${IMAGE_TAG} .
                    """
                }
            }
        }

        stage('Docker Push') {
            steps {
                withCredentials([
            usernamePassword(
                credentialsId: 'dockerhub',
                usernameVariable: 'rajvi1023',
                passwordVariable: 'motherisgod@1023'
            )
        ]) {
                    sh """
                echo \$DOCKER_PASSWORD | docker login \
                    -u \$DOCKER_USERNAME \
                    --password-stdin

                docker push ${IMAGE_NAME}:${IMAGE_TAG}
            """
        }
            }
        }

        stage('Deploy Kubernetes') {
            steps {
                sh """
                    kubectl set image deployment/dashboard-service \
                    dashboard-service=${IMAGE}:${TAG}

                    kubectl rollout status \
                    deployment/dashboard-service
                """
            }
        }
    }
}
