apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-gateway
  namespace: banking

spec:
  replicas: 1

  selector:
    matchLabels:
      app: api-gateway

  template:
    metadata:
      labels:
        app: api-gateway

    spec:

      # ==========================================================
      # POD SECURITY
      # ==========================================================

      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001


      # ==========================================================
      # CONTAINER
      # ==========================================================

      containers:

        - name: api-gateway

          image: ${FULL_IMAGE}
          imagePullPolicy: Always


          # ======================================================
          # CONTAINER SECURITY
          # ======================================================

          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            allowPrivilegeEscalation: false


          # ======================================================
          # PORT
          # ======================================================

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP


          # ======================================================
          # RESOURCES
          # ======================================================

          resources:

            requests:
              memory: "256Mi"
              cpu: "100m"

            limits:
              memory: "512Mi"
              cpu: "500m"


          # ======================================================
          # READINESS PROBE
          # ======================================================

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
              scheme: HTTP

            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1


          # ======================================================
          # LIVENESS PROBE
          # ======================================================

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
              scheme: HTTP

            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1