server:
  port: 8011

spring:
  application:
    name: FRAUD-DEDUCTION-SERVICE

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: fraud-deduction-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

        spring.json.use.type.headers: false
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.banking.fraud.detection.event.TransactionInitiatedEvent

account:
  service:
    url: http://localhost:8007

fraud:
  max-transaction-per-minute: 5
  suspicious-amount-multiplier: 5
  max-balance-percentage: 0.90

management:
  endpoints:
    web:
      exposure:
        include: health,info