apiVersion: apps/v1
kind: Deployment

metadata:
  name: employee-service
  namespace: employee

spec:
  replicas: 3

  selector:
    matchLabels:
      app: employee-service

  template:
    metadata:
      labels:
        app: employee-service

    spec:
      containers:

        - name: employee-service

          image: rajvi1023/employee-service:${IMAGE_TAG}

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080

          env:
            - name: DB_URL
              value: jdbc:mysql://mysql-service:3306/employeedb?useSSL=false&serverTimezone=UTC

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: employee-db-secret
                  key: username

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: employee-db-secret
                  key: password

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20