apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret       # ← actual Kubernetes resource name
  namespace: banking
type: Opaque

stringData:
  DB_USER: root
  DB_PASSWORD: root123
  DB_URL: jdbc:mysql://mysql.banking.svc.cluster.local:3306/auth_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC