apiVersion: policy/v1
kind: PodDistruptionBudget



metadata: 
   name: auth-service-pdb
   namespace: banking



spec: 
  minAvailable: 2


  selector: 
     matchLabels:
        app: auth-service
        