apiVersion: v1
kind: Secret

metadata:
  name: auth-service-secret
  namespace: banking

type: Opaque

stringData:
  DB_USER: root
  DB_PASSWORD: root123
  DB_URL: jdbc:mysql://mysql:3306/auth_db?useSSL=false&serverTimezone=UTC