apiVersion: v1
kind: ConfigMap

metadata:
  name: auth-service-config
  namespace: banking

data:
  SPRING_PROFILES_ACTIVE: local

  DB_URL: jdbc:mysql://localhost:3306/auth_db?useSSL=false&serverTimezone=UTC

  REDIS_HOST: redis
  REDIS_PORT: "6379"

  EUREKA_URL: http://eureka-server:8761/eureka/

  DB_POOL_MAX_SIZE: "10"
  DB_POOL_MIN_IDLE: "5"