apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-service
  namespace: banking

spec:
  replicas: 3

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: auth-service

  template:
    metadata:
      labels:
        app: auth-service

    spec:
      terminationGracePeriodSeconds: 30

      containers:
        - name: auth-service
          image: rajvi1023/auth-service:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8001
              protocol: TCP

          env:
            - name: DB_URL
              value: "jdbc:mysql://mysql:3306/auth_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: username

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: password

            - name: REDIS_HOST
              value: "redis"

            - name: REDIS_PORT
              value: "6379"

            - name: EUREKA_URL
              value: "http://eureka-server:8761/eureka/"

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3